#include "utils-hildon.h"

QMap<xcb_atom_t, QHildonIMAtom> HILDON_ATOM_MAP = {};

QStringList hildonAtomNames = {
  "HILDON_IM_WINDOW",
  "HILDON_IM_ACTIVATE",
  "HILDON_IM_INPUT_MODE",
  "HILDON_IM_INSERT_UTF8",
  "HILDON_IM_SURROUNDING",
  "HILDON_IM_SURROUNDING_CONTENT",
  "HILDON_IM_KEY_EVENT",
  "HILDON_IM_COM",
  "HILDON_IM_CLIPBOARD_COPIED",
  "HILDON_IM_CLIPBOARD_SELECTION_QUERY",
  "HILDON_IM_CLIPBOARD_SELECTION_REPLY",
  "HILDON_IM_PREEDIT_COMMITTED",
  "HILDON_IM_PREEDIT_COMMITTED_CONTENT",
  "HILDON_IM_LONG_PRESS_SETTINGS",
};
