#include "utils-hildon.h"

QMap<xcb_atom_t, QHildonIMAtom> HILDON_ATOM_MAP = {};
QMap<unsigned int, QHildonIMCom> HILDON_COM_MAP = {};

QStringList hildonAtomNames = {
  "HILDON_IM_WINDOW",
  "HILDON_IM_ACTIVATE",
  "HILDON_IM_INPUT_MODE",
  "HILDON_IM_INSERT_UTF8",
  "HILDON_IM_SURROUNDING",
  "HILDON_IM_SURROUNDING_CONTENT",
  "HILDON_IM_KEY_EVENT",
  "HILDON_IM_COM",
  "HILDON_IM_CLIPBOARD_COPIED",
  "HILDON_IM_CLIPBOARD_SELECTION_QUERY",
  "HILDON_IM_CLIPBOARD_SELECTION_REPLY",
  "HILDON_IM_PREEDIT_COMMITTED",
  "HILDON_IM_PREEDIT_COMMITTED_CONTENT",
  "HILDON_IM_LONG_PRESS_SETTINGS",
};

QStringList hildonComNames = {
  "HILDON_IM_CONTEXT_HANDLE_ENTER",
  "HILDON_IM_CONTEXT_HANDLE_TAB",
  "HILDON_IM_CONTEXT_HANDLE_BACKSPACE",
  "HILDON_IM_CONTEXT_HANDLE_SPACE",
  "HILDON_IM_CONTEXT_CONFIRM_SENTENCE_START",
  "HILDON_IM_CONTEXT_FLUSH_PREEDIT",
  "HILDON_IM_CONTEXT_CANCEL_PREEDIT",
  "HILDON_IM_CONTEXT_BUFFERED_MODE",
  "HILDON_IM_CONTEXT_DIRECT_MODE",
  "HILDON_IM_CONTEXT_REDIRECT_MODE",
  "HILDON_IM_CONTEXT_SURROUNDING_MODE",
  "HILDON_IM_CONTEXT_PREEDIT_MODE",
  "HILDON_IM_CONTEXT_CLIPBOARD_COPY",
  "HILDON_IM_CONTEXT_CLIPBOARD_CUT",
  "HILDON_IM_CONTEXT_CLIPBOARD_PASTE",
  "HILDON_IM_CONTEXT_CLIPBOARD_SELECTION_QUERY",
  "HILDON_IM_CONTEXT_REQUEST_SURROUNDING",
  "HILDON_IM_CONTEXT_REQUEST_SURROUNDING_FULL",
  "HILDON_IM_CONTEXT_WIDGET_CHANGED",
  "HILDON_IM_CONTEXT_OPTION_CHANGED",
  "HILDON_IM_CONTEXT_ENTER_ON_FOCUS",
  "HILDON_IM_CONTEXT_SPACE_AFTER_COMMIT",
  "HILDON_IM_CONTEXT_NO_SPACE_AFTER_COMMIT",
  "HILDON_IM_CONTEXT_SHIFT_LOCKED",
  "HILDON_IM_CONTEXT_SHIFT_UNLOCKED",
  "HILDON_IM_CONTEXT_LEVEL_LOCKED",
  "HILDON_IM_CONTEXT_LEVEL_UNLOCKED",
  "HILDON_IM_CONTEXT_SHIFT_UNSTICKY",
  "HILDON_IM_CONTEXT_LEVEL_UNSTICKY"
};
